// src/api/types/news.types.js
//
// Domain shape for a news item. The original data.json had separate
// `date` and `time` string fields (Persian calendar); these were merged
// into a single `publishedAt` ISO timestamp on the new schema, since
// that's far easier to sort/filter/format than two separate strings.

/**
 * @typedef {Object} NewsItem
 * @property {number} id
 * @property {string} label
 * @property {string} body
 * @property {string} publishedAt - ISO 8601 timestamp, e.g. "2026-06-26T17:27:05Z"
 */

/**
 * Shape used when creating a news item — `id` excluded since it's
 * auto-generated by the database (identity column).
 *
 * @typedef {Omit<NewsItem, 'id'>} NewNewsItem
 */

export {};
